In [13]:
import numpy as np

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[8]

8

In [17]:
arr[1:5]

array([1, 2, 3, 4])

In [18]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr[0:4] = 25

In [20]:
arr

array([25, 25, 25, 25,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_array = arr[:6] # here is very important

In [24]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [27]:
slice_of_array[:] = 99

In [28]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [29]:
arr # here is very important, also main array has changed.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])