In [1]:
my_list = [1, 2, 3, 4]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5,3)*10

array([[8.55651916, 6.39449929, 7.16231521],
       [7.83422316, 0.77808551, 9.50541398],
       [4.06961224, 6.62327283, 4.85288538],
       [3.84166137, 0.31585452, 4.20247033],
       [0.1048918 , 3.0257759 , 7.28962731]])

In [23]:
np.random.randn(4,4)

array([[-1.38062535,  1.2470978 , -0.12092224,  1.68087561],
       [-1.30081461, -0.89938876, -0.42763595, -0.58426075],
       [ 1.4923856 , -0.16825408, -1.3457751 , -0.33038921],
       [ 0.58967852, -0.10637742, -0.07980678, -0.9246935 ]])

In [24]:
np.random.randint(0,100)

98

In [25]:
np.random.randint(0,100,7)

array([19, 95, 86, 38,  6, 80, 29])

In [34]:
new_arr = np.random.randint(0,100,25)

In [35]:
new_arr

array([77, 12, 12, 23, 38, 36, 12, 35, 53, 12, 77, 83,  0,  4, 53, 22,  0,
       42,  3, 98, 40, 95, 66, 40, 18])

In [36]:
re_new_arr = new_arr.reshape(5,5)

In [37]:
re_new_arr

array([[77, 12, 12, 23, 38],
       [36, 12, 35, 53, 12],
       [77, 83,  0,  4, 53],
       [22,  0, 42,  3, 98],
       [40, 95, 66, 40, 18]])

In [38]:
re_new_arr.max()

98

In [41]:
re_new_arr.argmax()

19

In [42]:
re_new_arr.argmin()

12

In [44]:
from numpy.random import randint

In [47]:
randint(2,50)

43